### PR TITLE
fix: added samples folder; separate commands tng-workspace and tng-project

### PR DESCRIPTION
**Pull request by StefanUPB**
Added missing samples folder for `tng-project --project ...`

### CODE REVIEW

**Comment by StefanUPB** [comment]
It says command `docker` not found. Docker should be installed on Jenkins, right?

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
Now it passed. It was failling because new jenkins slave doesn't have docker installed.

**Pull request merged**
